[project]
name = "nicar26-pdf-cli-advanced"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "pdfplumber>=0.11.9",
    "pydantic>=2.12.5",
]
